language: python
python:
  - "2.7"
env:
  - TOX_ENV=pypy-djdev
  - TOX_ENV=py3.4-djdev
  - TOX_ENV=py3.3-djdev
  - TOX_ENV=py3.2-djdev
  - TOX_ENV=py2.7-djdev
  - TOX_ENV=pypy-dj1.6
  - TOX_ENV=py3.3-dj1.6
  - TOX_ENV=py3.2-dj1.6
  - TOX_ENV=py2.7-dj1.6
  - TOX_ENV=py2.6-dj1.6
  - TOX_ENV=pypy-dj1.5
  - TOX_ENV=py3.3-dj1.5
  - TOX_ENV=py3.2-dj1.5
  - TOX_ENV=py2.7-dj1.5
  - TOX_ENV=py2.6-dj1.5
  - TOX_ENV=pypy-dj1.4
  - TOX_ENV=py2.7-dj1.4
  - TOX_ENV=py2.6-dj1.4
  - TOX_ENV=coverage
install:
  - pip install tox==1.7.2 coveralls==0.4.2
script:
  - tox -e $TOX_ENV
notifications:
  email: false
branches:
  only:
    - master
after_success:
  coveralls