language: python
python:
  - "2.7"
env:
  - TOX_ENV=pypy-djdev,py3.4-djdev,py2.7-djdev
  - TOX_ENV=pypy-dj1.6,py3.3-dj1.6,py2.7-dj1.6
  - TOX_ENV=pypy-dj1.5,py3.3-dj1.5,py2.7-dj1.5
  - TOX_ENV=pypy-dj1.4,py2.7-dj1.4
install:
  - pip install tox==1.7.1
addons:
  postgresql: "9.3"  
script:
  - tox -e $TOX_ENV
  - DATABASE_USER="postgres" DATABASE_PASSWORD="" tox -e $TOX_ENV postgres
  - DATABASE_USER="travis" DATABASE_PASSWORD="" tox -e $TOX_ENV mysql
notifications:
  email: false
branches:
  only:
    - develop
    - master
