language: python
cache: pip

python:
  - "2.7"
  - "3.5"

env:
  global:
    - TRAVIS=true
  matrix:
    - TOX_ENV=py35-dj1.11-postgres
    - TOX_ENV=py27-dj1.11-postgres
    - TOX_ENV=py35-dj1.11-sqlite
    - TOX_ENV=py27-dj1.11-sqlite
    - TOX_ENV=py35-dj1.11-mysql
    - TOX_ENV=py27-dj1.11-mysql 
    - TOX_ENV=py35-dj1.10-sqlite
    - TOX_ENV=py27-dj1.10-sqlite  
    - TOX_ENV=py35-dj1.10-mysql
    - TOX_ENV=py27-dj1.10-mysql
    - TOX_ENV=py35-dj1.10-postgres
    - TOX_ENV=py27-dj1.10-postgres
    - TOX_ENV=py35-dj1.9-sqlite
    - TOX_ENV=py27-dj1.9-sqlite  
    - TOX_ENV=py35-dj1.9-mysql
    - TOX_ENV=py27-dj1.9-mysql
    - TOX_ENV=py35-dj1.9-postgres
    - TOX_ENV=py27-dj1.9-postgres  
    - TOX_ENV=py35-dj1.8-sqlite
    - TOX_ENV=py27-dj1.8-sqlite    
    - TOX_ENV=coverage
install:
  - pip install tox coveralls
services:
  - mysql
  - postgresql  
addons:
  postgresql: "9.5"
script:
  - tox -e $TOX_ENV
notifications:
  email: false
branches:
  only:
    - master
after_success:
  coveralls
