# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0002_remove_action_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_object_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='actor_object_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='action',
            name='target_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_object_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='actor_object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='target_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        )
    ]
