# Generated by Django 3.0.8 on 2020-07-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0003_integer_pks'),
        ('actstream', '0003_add_follow_flag'),
    ]

    operations = [
    ]
